removida guarda do servidor

diff --git a/.github/workflows/evaluation.yml b/.github/workflows/evaluation.yml
--- a/.github/workflows/evaluation.yml
+++ b/.github/workflows/evaluation.yml
@@ -24,33 +24,31 @@ jobs:
       - name: Build e Run do Container Docker
         env:
           GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
-          CONFIDENT_API_KEY: ${{ secrets.CONFIDENT_API_KEY }}
           GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
         run: |
           echo "Building Docker image..."
           docker build -t chatbot-api .
           
           echo "Starting Docker container in background..."
-          docker run -d -p 8080:8080 --name chatbot-container -e GROQ_API_KEY -e CONFIDENT_API_KEY -e GOOGLE_API_KEY chatbot-api
+          docker run -d -p 8080:8080 --name chatbot-container -e GROQ_API_KEY -e GOOGLE_API_KEY chatbot-api
       
-      - name: Aguardar o Servidor da Aplicação (Health Check)
-        run: |
-          echo "Waiting for application server to be ready..."
-          timeout=120
-          while ! curl -s --fail http://localhost:8080/docs; do
-            sleep 2
-            timeout=$((timeout - 2))
-            if [ $timeout -le 0 ]; then
-              echo "Timed out waiting for server."
-              echo "Displaying container logs for debugging..."
-              docker logs chatbot-container
-              exit 1
-            fi
-          done
-          echo "Server is up and running!"
+      # - name: Aguardar o Servidor da Aplicação (Health Check)
+      #   run: |
+      #     echo "Waiting for application server to be ready..."
+      #     timeout=120
+      #     while ! curl -s --fail http://localhost:8080/docs; do
+      #       sleep 2
+      #       timeout=$((timeout - 2))
+      #       if [ $timeout -le 0 ]; then
+      #         echo "Timed out waiting for server."
+      #         echo "Displaying container logs for debugging..."
+      #         docker logs chatbot-container
+      #         exit 1
+      #       fi
+      #     done
+      #     echo "Server is up and running!"
       - name: Login e Execução dos Testes do DeepEval
         env:
-          CONFIDENT_API_KEY: ${{ secrets.CONFIDENT_API_KEY }}
           GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
           GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
         run: |
@@ -109,7 +107,6 @@ jobs:
           echo "Starting new container..."
           docker run -d -p 8080:8080 --name chatbot-container \
             -e GROQ_API_KEY='${{ secrets.GROQ_API_KEY }}' \
-            -e CONFIDENT_API_KEY='${{ secrets.CONFIDENT_API_KEY }}' \
             -e GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}' \
             ghcr.io/${{ github.repository_owner }}/chatbot-api:latest
           
